M48
; DRILL file {KiCad 7.0.9} date Tuesday, March 05, 2024 at 03:29:16 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-05T03:29:16-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.0039Y-4.7677
X4.0079Y-2.5394
X5.9008Y-2.5433
X5.9094Y-4.7677
T0
M30
