M48
; DRILL file {KiCad 7.0.9} date Tuesday, March 19, 2024 at 03:39:18 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-19T15:39:18-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.937Y-4.6063
X3.6063Y-2.5354
X3.8189Y-4.2362
X4.4488Y-3.5433
T0
M30
